<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.9" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\favicon.png" />
    <Content Remove="wwwroot\icon-192.png" />
    <Content Remove="wwwroot\icon-512.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hatchly.Core\Hatchly.Core.csproj" />
  </ItemGroup>

</Project>
